global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8087'] #replace localhost to IPv4
        labels:
          application: 'Product Service Application'
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8089'] #replace localhost to IPv4
        labels:
          application: 'Order Service Application'
  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8082'] #replace localhost to IPv4
        labels:
          application: 'Inventory Service Application'
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8086'] #replace localhost to IPv4
        labels:
          application: 'Notification Service Application'
  - job_name: 'message-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8091' ] #replace localhost to IPv4
        labels:
          application: 'Message Service Application'